### ISSUE TITLE
ribotish tisdiff error?ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by lei025** [zhpn1024/ribotish#16]
hi,when I use the ribotish tisdiff ,some error information as follows:
my command :
ribotish tisdiff -1 pred1.txt -2 pred2.txt -a v1.sort.bam -b vi2.sort.bam -g test.gtf -o diff -v
error informations:

Loading 2 TIS data...
1 TISs in pred1.txt.
1 TISs in pred2.txt.
1 TISs in total.
Reading bams...
JN
Estimate scale factor...
Traceback (most recent call last):
  File "/usr/bin/ribotish", line 4, in <module>
    __import__('pkg_resources').run_script('ribotish==0.2.6', 'ribotish')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 654, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1441, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/ribotish-0.2.6-py2.7.egg/EGG-INFO/scripts/ribotish", line 56, in <module>
    
  File "/usr/lib/python2.7/site-packages/ribotish-0.2.6-py2.7.egg/EGG-INFO/scripts/ribotish", line 34, in main
    
  File "build/bdist.linux-x86_64/egg/ribotish/run/tisdiff.py", line 254, in run
  File "build/bdist.linux-x86_64/egg/ribotish/zbio/exp.py", line 207, in TMM
ZeroDivisionError: integer division or modulo by zero

**Comment by lei025** [comment]
the files pred1.txt , pred2.txt , v1.sort.bam , vi2.sort.bam are in the same fold ?

**Comment by zhpn1024** [comment]
1 TISs in pred1.txt.
1 TISs in pred2.txt.
1 TISs in total.

Why there is only one TIS?

**Comment by zhpn1024** [comment]
The error is because the number of TISs are too small, and result in fail of normalization.

**Comment by lei025** [comment]
![image](https://user-images.githubusercontent.com/26000187/111569556-d9692180-87dd-11eb-945d-fdd55838f54a.png)
hi,using this tool how to get the picture ?

**Comment by lei025** [comment]
the number of  TISs is more than 100.How many at least ?

**Comment by zhpn1024** [comment]
The log showed only one TIS selected. Do you use the full transcript annotation?
The figure is generated in another script. I'll update later.

**Comment by shwdmsh** [comment]
Why there is only one TIS? @zhpn1024 The genome is virus. There is some error?

**Comment by zhpn1024** [comment]
There are filters to select significant TISs (--ipth --iqth).

**Comment by zhpn1024** [comment]
It is difficult to open github these days.

**Comment by shwdmsh** [comment]
@zhpn1024 thanks .I will try these parameters.
