### ISSUE TITLE
run mistakes

### ISSUE THREAD

**Issue by czppeter** [zhpn1024/ribotish#25]
Traceback (most recent call last):
  File "/gss1/home/zpchen/miniconda3/envs/ribotish/bin/ribotish", line 56, in <module>
    main()
  File "/gss1/home/zpchen/miniconda3/envs/ribotish/bin/ribotish", line 34, in main
    commands[cmd].run(args)
  File "/gss1/home/zpchen/miniconda3/envs/ribotish/lib/python2.7/site-packages/ribotish/run/quality.py", line 85, in run
    cdsBins = args.bins, numProc = args.numProc, verbose = args.verbose, geneformat = args.geneformat)
  File "/gss1/home/zpchen/miniconda3/envs/ribotish/lib/python2.7/site-packages/ribotish/zbio/ribo.py", line 980, in lendis
    for result in len_iter:
  File "/gss1/home/zpchen/miniconda3/envs/ribotish/lib/python2.7/site-packages/ribotish/zbio/ribo.py", line 942, in _lendis_trans
    for r in bam.transReadsIter(bamfile, t, compatible=False, maxNH=maxNH, minMapQ=minMapQ, secondary=secondary, paired=paired, flank=flank):
  File "/gss1/home/zpchen/miniconda3/envs/ribotish/lib/python2.7/site-packages/ribotish/zbio/bam.py", line 498, in transReadsIter
    for read in rds: #yield read
  File "/gss1/home/zpchen/miniconda3/envs/ribotish/lib/python2.7/site-packages/ribotish/zbio/bam.py", line 52, in fetch_reads
    if minMapQ is not None and read.mapping_quality < minMapQ : continue
AttributeError: 'csamtools.AlignedRead' object has no attribute 'mapping_quality'

**Comment by zhpn1024** [comment]
What's your pysam version?

**Comment by zhpn1024** [comment]
> 

I mean pysam. The latest version of pysam is 0.18.0

**Comment by czppeter** [comment]
pysam (0.6)
