### ISSUE TITLE
Error running ribotish predict with multicore parameters

### ISSUE THREAD

**Issue by elabaronne** [zhpn1024/ribotish#3]
Hi, 
I'm trying to use the whole pipeline of ribotish. When I run the command 
`ribotish predict -t unassigned_HARR_mapped_sort.bam -b unassigned_mapped_sort.bam -g ../gencode/gencode.v28.annotation_appris_princ_1.gtf -f ../gencode/GRCh38.p12.genome.fa -o unassigned_pred.txt -p 8`
i get this error : 
`Thu Jun 27 17:21:06 2019 Estimating TIS background parameters...
Traceback (most recent call last):
  File "/home/adminmanu/softwares/miniconda3/bin/ribotish", line 56, in <module>
    main()
  File "/home/adminmanu/softwares/miniconda3/bin/ribotish", line 34, in main
    commands[cmd].run(args)
  File "/home/adminmanu/softwares/miniconda3/lib/python3.7/site-packages/ribotish/run/predict.py", line 151, in run
    pool = MyPool(1) # This is for memory efficiency
  File "/home/adminmanu/softwares/miniconda3/lib/python3.7/multiprocessing/pool.py", line 177, in __init__
    self._repopulate_pool()
  File "/home/adminmanu/softwares/miniconda3/lib/python3.7/multiprocessing/pool.py", line 238, in _repopulate_pool
    self._wrap_exception)
  File "/home/adminmanu/softwares/miniconda3/lib/python3.7/multiprocessing/pool.py", line 252, in _repopulate_pool_static
    wrap_exception)
  File "/home/adminmanu/softwares/miniconda3/lib/python3.7/multiprocessing/process.py", line 74, in __init__
    assert group is None, 'group argument must be None for now'
AssertionError: group argument must be None for now`

This error did not occur when I use the same command without the -p parameters so I can continue with downstream analysis using one core.

I'm using ribotish with python 3.7 

Thanks

**Comment by zhpn1024** [comment]
It may be a problem only in the new version of python. I will check it.
The error may only occur when generating .bgest.txt file using multiprocessing. If you have already generated the .bgest.txt background file using one CPU, this step will be skipped, and you may use multiprocessing without error.

**Comment by zhpn1024** [comment]
The error is probably because your multiprocessing module is not up-to-date for python 3.7.
