### ISSUE TITLE
ValueError: start out of range (-21) running ribotish quality

### ISSUE THREAD

**Issue by rbmk1000** [zhpn1024/ribotish#9]
I am new to ribotish - and want to run the quality command. This may be a trivial error to fix - advice appreciated.

$ ribotish quality -b /media/mrbmk1000/data/ms-pool01/C_neoformans/ribo-seq/star_sandbox_01/rbmk1000-4-59-1_S1_L00X_R1_001_trimmed_811_final_Aligned.sortedByCoord.out.bam -g /media/mrbmk1000/data/ms-pool01/annotationdb/cneoformans/FungiDB-38_CneoformansH99.gtf
Traceback (most recent call last):
  File "/home/mrbmk1000/miniconda3/bin/ribotish", line 56, in <module>
    main()
  File "/home/mrbmk1000/miniconda3/bin/ribotish", line 34, in main
    commands[cmd].run(args)
  File "/home/mrbmk1000/miniconda3/lib/python3.7/site-packages/ribotish/run/quality.py", line 85, in run
    cdsBins = args.bins, numProc = args.numProc, verbose = args.verbose, geneformat = args.geneformat)
  File "/home/mrbmk1000/miniconda3/lib/python3.7/site-packages/ribotish/zbio/ribo.py", line 980, in lendis
    for result in len_iter:
  File "/home/mrbmk1000/miniconda3/lib/python3.7/site-packages/ribotish/zbio/ribo.py", line 942, in _lendis_trans
    for r in bam.transReadsIter(bamfile, t, compatible=False, maxNH=maxNH, minMapQ=minMapQ, secondary=secondary, paired=paired, flank=flank):
  File "/home/mrbmk1000/miniconda3/lib/python3.7/site-packages/ribotish/zbio/bam.py", line 496, in transReadsIter
    for read in rds: #yield read
  File "/home/mrbmk1000/miniconda3/lib/python3.7/site-packages/ribotish/zbio/bam.py", line 45, in fetch_reads
    rds = self.fetch(reference=chr, start=start, end=stop) #, multiple_iterators=multiple_iterators)
  File "pysam/libcalignmentfile.pyx", line 1081, in pysam.libcalignmentfile.AlignmentFile.fetch
  File "pysam/libchtslib.pyx", line 691, in pysam.libchtslib.HTSFile.parse_region
ValueError: start out of range (-21)

Thank you for guidance.

**Comment by zhpn1024** [comment]
I have known the error. I will fix it soon.

**Comment by rbmk1000** [comment]
Thank you!

**Comment by zhpn1024** [comment]
Update to v0.2.5 and try again.

**Comment by rbmk1000** [comment]
I updated with:
pip install -U ribotish
v0.2.5 ran the quality command perfectly
Thank you for solving this.
